name: Run unit + integration tests on server
on:
  workflow_dispatch:

concurrency:
  group: "server_deploy"
  cancel-in-progress: false

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Setup certificate and secrets for Server instance
        run: |
            dotnet dev-certs https --trust -ep online/secrets/localhost.pfx -p DEVELOPMENT
            echo "{}" >> online/secrets/secrets.json
        
      - name: Build and run image 
        run: | 
            cd online
            docker compose -p interludeweb up --build --detach
            cd ..
        
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Unit tests
        run: dotnet test -v q online/tests/domain/Interlude.Web.Tests.Domain.fsproj
        
      - name: Integration tests
        run: |
            docker logs server
            dotnet test -v q online/tests/integration/Interlude.Web.Tests.Integration.fsproj
          
      - name: Log in to DigitalOcean registry 
        run: doctl registry login --expiry-seconds 600
        
      - name: Tag and push image
        run: |
          docker stop server
          docker tag docker.io/library/interludeweb-server registry.digitalocean.com/yavsrg/interlude-web-server:latest
          docker push registry.digitalocean.com/yavsrg/interlude-web-server:latest
            
      - name: Run garbage collection on DigitalOcean registry
        run: doctl registry garbage-collection start --force --include-untagged-manifests