name: Check suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Everything must build
      run: dotnet build
        
    - name: Unit tests must pass
      run: |
        cd scripts
        chmod +x ./run_tests.sh
        ./run_tests.sh